const pump = [
    {
        "name": "ปั๊มน้ำดิบ 1",
        "id": "1",
        "topicControl": "tabwater/device/1/control",
        "topicData": "tabwater/device/1/data",
        "topicAlive": "tabwater/device/1/alive",
        "alive": "",
        "overload": "t", 
        "voltage": "1500", 
        "current": "10", 
        "power": "1500.00", 
        "energy": "", 
        "frequency": "", 
        "pf":"",
        "temperature":"89",
        "flowRate":"100",
        "value": "close",
    },
    {
        "name": "ปั๊มน้ำแรงดันสูง",
        "id": "3",
        "topicControl": "tabwater/device/3/control",
        "topicData": "tabwater/device/3/data",
        "topicAlive": "tabwater/device/3/alive",
        "alive": "online",
        "overload": "", 
        "voltage": "", 
        "current": "9.9", 
        "power": "800", 
        "energy": "", 
        "frequency": "", 
        "pf":"",
        "temperature":"",
        "flowRate":"",
        "value": "close",
    }
]

module.exports = pump;